#!/usr/bin/env bash

git submodule update --init --recursive

SCRIPT_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

RECIPES_PATH="${SCRIPT_ROOT}/.dotfiles/recipes"
source "${RECIPES_PATH}/link.sh"
